
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SABIT_KARAEV
 */
public class JFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame1
     */
    public JFrame1() {
        initComponents();
        jLabel6.setText("Выбранно:");
        jLabel10.setText("Выбранно:");
        jLabel12.setText("Выбранно:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFrame4 = new javax.swing.JFrame();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFrame5 = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame2.setTitle("Мое детство");
        jFrame2.setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("icon.png"))
        );
        jFrame2.setMinimumSize(new java.awt.Dimension(818, 747));
        jFrame2.setResizable(false);
        jFrame2.getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setText("Назад");
        jButton3.setToolTipText("Вернуться на стартовую страницу");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton3);
        jButton3.setBounds(30, 640, 360, 40);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setText("Далее");
        jButton4.setToolTipText("Перейти к следующему вопросу");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton4);
        jButton4.setBounds(410, 640, 360, 40);

        jList1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Superman", "Batman", "Flash", "Wonder Woman", "Green Lantern", "Aquaman", "Ironman", "Capitan America", "Hulk", "Wolverine", "Black Widow", "Thor", "Kakashi sensei", "Jiraiya sensei", "Naruto", "Sasuke", "Gaara" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setAutoscrolls(false);
        jList1.setSelectedIndex(0);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jFrame2.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 190, 440);
        jFrame2.getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 110, 550, 410);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jFrame2.getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 590, 740, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("Ваш любимый персонаж комиксов/аниме?");
        jFrame2.getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 14, 740, 50);

        jFrame2.setLocationRelativeTo(null);

        jFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame3.setTitle("Мое отрочество");
        jFrame3.setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("icon.png"))
        );
        jFrame3.setMinimumSize(new java.awt.Dimension(818, 747));
        jFrame3.setResizable(false);
        jFrame3.getContentPane().setLayout(null);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton5.setText("Назад");
        jButton5.setToolTipText("Вернуться к предыдущему вопросу");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton5);
        jButton5.setBounds(30, 640, 360, 40);

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton6.setText("Далее");
        jButton6.setToolTipText("Перейти к следующему вопросу");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton6);
        jButton6.setBounds(410, 640, 360, 40);

        jComboBox1.setMaximumRowCount(15);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dota ", "Counter Strike", "Assissin's Creed", "Grand Theft Auto ", "Fallout", "The Elder Scrolls", "Dead Space", "The Witcher", "Watch Dogs", "Mass Effect", "Battlefield", "S.T.A.L.K.E.R.", "HALO", "Dragon Age", "Diablo", "Half-Life", "Dark Souls", "The Sims", "Call of Duty", "Heroes of Might and Magic", "DOOM", "Crysis" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(30, 60, 740, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Ваша любимая серия игр?");
        jFrame3.getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 14, 740, 50);
        jFrame3.getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 130, 510, 420);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jFrame3.getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 590, 740, 40);

        jFrame3.setLocationRelativeTo(null);

        jFrame4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame4.setTitle("Моя юность");
        jFrame4.setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("icon.png"))
        );
        jFrame4.setMinimumSize(new java.awt.Dimension(818, 747));
        jFrame4.setResizable(false);
        jFrame4.getContentPane().setLayout(null);

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton7.setText("Назад");
        jButton7.setToolTipText("Вернуться к предыдущему вопросу");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton7);
        jButton7.setBounds(30, 640, 360, 40);

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton8.setText("Далее");
        jButton8.setToolTipText("Перейти к следующему вопросу");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton8);
        jButton8.setBounds(410, 640, 360, 40);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton1.setText("DeLorian");
        jRadioButton1.setToolTipText("Фильм \"Назад в будущее\"");
        jRadioButton1.setActionCommand("0");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(60, 100, 180, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton2.setText("Chevrolet Impala");
        jRadioButton2.setToolTipText("Cериал \"Сверхъестественное\"");
        jRadioButton2.setActionCommand("1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(60, 170, 180, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton3.setText("Nissan Skyline GT-R");
        jRadioButton3.setToolTipText("Фильм \"Форсаж 2\"");
        jRadioButton3.setActionCommand("2");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(60, 240, 180, 25);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Chevrolet Camaro");
        jRadioButton4.setToolTipText("Фильм \"Трансформеры\"");
        jRadioButton4.setActionCommand("3");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(60, 310, 180, 25);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("General Lee");
        jRadioButton5.setToolTipText("Фильм \"Придурки из Хазарда\"");
        jRadioButton5.setActionCommand("4");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(60, 380, 180, 25);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Batmobile");
        jRadioButton6.setToolTipText("Фильм \"Лига справедливости\"");
        jRadioButton6.setActionCommand("5");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(60, 450, 180, 25);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Dodge Charger");
        jRadioButton7.setToolTipText("Фильм \"Форсаж\"");
        jRadioButton7.setActionCommand("6");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(60, 520, 180, 25);
        jFrame4.getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 110, 510, 420);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jFrame4.getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 590, 740, 40);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("Машина на которой вы бы прокатились?");
        jFrame4.getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 14, 740, 50);

        jFrame4.setLocationRelativeTo(null);

        jFrame5.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame5.setTitle("Спасибо!");
        jFrame5.setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("icon.png"))
        );
        jFrame5.setMinimumSize(new java.awt.Dimension(818, 747));
        jFrame5.setResizable(false);
        jFrame5.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jFrame5WindowActivated(evt);
            }
        });
        jFrame5.getContentPane().setLayout(null);

        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton9.setText("Назад");
        jButton9.setToolTipText("Вернуться к последнему вопросу");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton9);
        jButton9.setBounds(30, 640, 360, 40);

        jButton10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton10.setText("Выход");
        jButton10.setToolTipText("Закончить тестирование");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton10);
        jButton10.setBounds(410, 640, 360, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel14.setText("Ваши ответы");
        jFrame5.getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 14, 740, 50);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ваш любимый персонаж комиксов/аниме?", null},
                {"Ваша любимая серия игр?", null},
                {"Машина на которой вы бы прокатились?", null}
            },
            new String [] {
                "Вопрос", "Ответ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoscrolls(false);
        jTable1.setRowHeight(30);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jFrame5.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 80, 720, 130);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel15.setText("Спасибо за тестирование!");
        jFrame5.getContentPane().add(jLabel15);
        jLabel15.setBounds(190, 270, 430, 50);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Нажмите \"Назад\" чтобы вернуться к последнему вопросу.");
        jFrame5.getContentPane().add(jLabel16);
        jLabel16.setBounds(180, 330, 460, 22);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Нажмите \"Выход\" для завершения тестирования.");
        jFrame5.getContentPane().add(jLabel17);
        jLabel17.setBounds(180, 360, 450, 22);

        jFrame5.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Приветствие");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("icon.png"))
        );
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Выход");
        jButton1.setToolTipText("Закрыть программу");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 640, 360, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("Старт");
        jButton2.setToolTipText("Начать тестирование");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 640, 360, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 72)); // NOI18N
        jLabel1.setText("Добро пожаловать!");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 240, 600, 80);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Вас приветствует система быстроо анкетирования.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 330, 530, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Нажмите \"Старт\" чтобы начать тестирование.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 370, 520, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Нажмите \"Выход\" чтобы закрыть программу.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 400, 370, 22);

        setSize(new java.awt.Dimension(818, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        jFrame2.setVisible(true);
        jList1MousePressed(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFrame2.setVisible(false);
        this.setVisible(true);
        jList1.setSelectedIndex(0);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jComboBox1ActionPerformed(null);
        jFrame2.setVisible(false);
        jFrame3.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFrame3.setVisible(false);
        jFrame2.setVisible(true);
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jRadioButton1ActionPerformed(null);
        jRadioButton1.setSelected(true);
        jFrame3.setVisible(false);
        jFrame4.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jFrame4.setVisible(false);
        jFrame3.setVisible(true);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jFrame4.setVisible(false);
        jFrame5.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jFrame5.setVisible(false);
        jFrame4.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        switch (jList1.getSelectedIndex()) {
            case 0: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Superman.png")));
                jLabel6.setText("Выбранно: Superman");
            }
            break;
            case 1: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Batman.png")));
                jLabel6.setText("Выбранно: Batman");
            }
            break;
            case 2: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Flash.png")));
                jLabel6.setText("Выбранно: Flash");
            }
            break;
            case 3: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Wonder Woman.png")));
                jLabel6.setText("Выбранно: Wonder Woman");
            }
            break;
            case 4: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Green Lantern.png")));
                jLabel6.setText("Выбранно: Green Lantern");
            }
            break;
            case 5: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Aquaman.png")));
                jLabel6.setText("Выбранно: Aquaman");
            }
            break;
            case 6: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Ironman.png")));
                jLabel6.setText("Выбранно: Ironman");
            }
            break;
            case 7: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Capitan America.png")));
                jLabel6.setText("Выбранно: Capitan America");
            }
            break;
            case 8: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Hulk.png")));
                jLabel6.setText("Выбранно: Hulk");
            }
            break;
            case 9: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Wolverine.png")));
                jLabel6.setText("Выбранно: Wolverine");
            }
            break;
            case 10: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Black Widow.png")));
                jLabel6.setText("Выбранно: Black Widow");
            }
            break;
            case 11: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Thor.png")));
                jLabel6.setText("Выбранно: Thor");
            }
            break;
            case 12: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Kakashi sensei.png")));
                jLabel6.setText("Выбранно: Kakashi sensei");
            }
            break;
            case 13: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Jiraiya sensei.png")));
                jLabel6.setText("Выбранно: Jiraiya sensei");
            }
            break;
            case 14: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Naruto.png")));
                jLabel6.setText("Выбранно: Naruto");
            }
            break;
            case 15: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Sasuke.png")));
                jLabel6.setText("Выбранно: Sasuke");
            }
            break;
            default: {
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame2/Gaara.png")));
                jLabel6.setText("Выбранно: Gaara");
            }
        }
    }//GEN-LAST:event_jList1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        switch (jComboBox1.getSelectedIndex()) {
            case 0: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Dota.png")));
                jLabel10.setText("Выбранно: Dota");
            }
            break;
            case 1: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Counter Strike.png")));
                jLabel10.setText("Выбранно: Counter Strike");
            }
            break;
            case 2: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Assasin's Creed.png")));
                jLabel10.setText("Выбранно: Assassin's Creed");
            }
            break;
            case 3: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Grand Theft Auto.png")));
                jLabel10.setText("Выбранно: Grand Theft Auto");
            }
            break;
            case 4: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Fallout.png")));
                jLabel10.setText("Выбранно: Fallout");
            }
            break;
            case 5: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/The Elder Scrolls.png")));
                jLabel10.setText("Выбранно: The Elder Scrolls");
            }
            break;
            case 6: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Dead Space.png")));
                jLabel10.setText("Выбранно: Dead Space");
            }
            break;
            case 7: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/The Witcher.png")));
                jLabel10.setText("Выбранно: The Witcher");
            }
            break;
            case 8: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Watch Dogs.png")));
                jLabel10.setText("Выбранно: Watch Dogs");
            }
            break;
            case 9: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Mass Effect.png")));
                jLabel10.setText("Выбранно: Mass Effect");
            }
            break;
            case 10: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Battlefield.png")));
                jLabel10.setText("Выбранно: Battlefield");
            }
            break;
            case 11: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/S.T.A.L.K.E.R..png")));
                jLabel10.setText("Выбранно: S.T.A.L.K.E.R.");
            }
            break;
            case 12: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/HALO.png")));
                jLabel10.setText("Выбранно: HALO");
            }
            break;
            case 13: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Dragon Age.png")));
                jLabel10.setText("Выбранно: Dragon Age");
            }
            break;
            case 14: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Diablo.png")));
                jLabel10.setText("Выбранно: Diablo");
            }
            break;
            case 15: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Half-Life.png")));
                jLabel10.setText("Выбранно: Half-Life");
            }
            break;
            case 16: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Dark Souls.png")));
                jLabel10.setText("Выбранно: Dark Souls");
            }
            break;
            case 17: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/The Sims.png")));
                jLabel10.setText("Выбранно: The Sims");
            }
            break;
            case 18: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Call of Duty.png")));
                jLabel10.setText("Выбранно: Call of Duty");
            }
            break;
            case 19: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Heroes of Might and Magic.png")));
                jLabel10.setText("Выбранно: Heroes of Might and Magic");
            }
            break;
            case 20: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/DOOM.png")));
                jLabel10.setText("Выбранно: DOOM");
            }
            break;
            default: {
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame3/Crysis.png")));
                jLabel10.setText("Выбранно: Crysis");
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame4/Batmobile.png")));
        jLabel12.setText("Выбранно: Batmobile");
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame4/DeLorian.png")));
        jLabel12.setText("Выбранно: DeLorian");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame4/Chevrolet Impala.png")));
        jLabel12.setText("Выбранно: Chevrolet Impala");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame4/Nissan Skyline GT-R.png")));
        jLabel12.setText("Выбранно: Nissan Skyline GT-R");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame4/Chevrolet Camaro.png")));
        jLabel12.setText("Выбранно: Chevrolet Camaro");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame4/General Lee.png")));
        jLabel12.setText("Выбранно: General Lee");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("Frame4/Dodge Charger.png")));
        jLabel12.setText("Выбранно: Dodge Charger");
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jFrame5WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame5WindowActivated
        switch (jList1.getSelectedIndex()) {
            case 0: {
                jTable1.setValueAt("Superman", 0, 1);
            }
            break;
            case 1: {
                jTable1.setValueAt("Batman", 0, 1);
            }
            break;
            case 2: {
                jTable1.setValueAt("Flash", 0, 1);
            }
            break;
            case 3: {
                jTable1.setValueAt("Wonder Woman", 0, 1);
            }
            break;
            case 4: {
                jTable1.setValueAt("Green Lantern", 0, 1);
            }
            break;
            case 5: {
                jTable1.setValueAt("Aquaman", 0, 1);
            }
            break;
            case 6: {
                jTable1.setValueAt("Ironman", 0, 1);
            }
            break;
            case 7: {
                jTable1.setValueAt("Capitan America", 0, 1);
            }
            break;
            case 8: {
                jTable1.setValueAt("Hulk", 0, 1);
            }
            break;
            case 9: {
                jTable1.setValueAt("Wolverine", 0, 1);
            }
            break;
            case 10: {
                jTable1.setValueAt("Black Widow", 0, 1);
            }
            break;
            case 11: {
                jTable1.setValueAt("Thor", 0, 1);
            }
            break;
            case 12: {
                jTable1.setValueAt("Kakashi sensei", 0, 1);
            }
            break;
            case 13: {
                jTable1.setValueAt("Jiraiya sensei", 0, 1);
            }
            break;
            case 14: {
                jTable1.setValueAt("Naruto", 0, 1);
            }
            break;
            case 15: {
                jTable1.setValueAt("Sasuke", 0, 1);
            }
            break;
            default: {
                jTable1.setValueAt("Gaara", 0, 1);
            }
        }
        switch (jComboBox1.getSelectedIndex()) {
            case 0: {
                jTable1.setValueAt("Dota", 1, 1);
            }
            break;
            case 1: {
                jTable1.setValueAt("Counter Strike", 1, 1);
            }
            break;
            case 2: {
                jTable1.setValueAt("Assassin's Creed", 1, 1);
            }
            break;
            case 3: {
                jTable1.setValueAt("Grand Theft Auto", 1, 1);
            }
            break;
            case 4: {
                jTable1.setValueAt("Fallout", 1, 1);
            }
            break;
            case 5: {
                jTable1.setValueAt("The Elder Scrolls", 1, 1);
            }
            break;
            case 6: {
                jTable1.setValueAt("Dead Space", 1, 1);
            }
            break;
            case 7: {
                jTable1.setValueAt("The Witcher", 1, 1);
            }
            break;
            case 8: {
                jTable1.setValueAt("Watch Dogs", 1, 1);
            }
            break;
            case 9: {
                jTable1.setValueAt("Mass Effect", 1, 1);
            }
            break;
            case 10: {
                jTable1.setValueAt("Battlefield", 1, 1);
            }
            break;
            case 11: {
                jTable1.setValueAt("S.T.A.L.K.E.R.", 1, 1);
            }
            break;
            case 12: {
                jTable1.setValueAt("HALO", 1, 1);
            }
            break;
            case 13: {
                jTable1.setValueAt("Dragon Age", 1, 1);
            }
            break;
            case 14: {
                jTable1.setValueAt("Diablo", 1, 1);
            }
            break;
            case 15: {
                jTable1.setValueAt("Half-Life", 1, 1);
            }
            break;
            case 16: {
                jTable1.setValueAt("Dark Souls", 1, 1);
            }
            break;
            case 17: {
                jTable1.setValueAt("The Sims", 1, 1);
            }
            break;
            case 18: {
                jTable1.setValueAt("Call of Duty", 1, 1);
            }
            break;
            case 19: {
                jTable1.setValueAt("Heroes of Might and Magic", 1, 1);
            }
            break;
            case 20: {
                jTable1.setValueAt("DOOM", 1, 1);
            }
            break;
            default: {
                jTable1.setValueAt("Crysis", 1, 1);
            }
        }
        switch (buttonGroup1.getSelection().getActionCommand()) {
            case "0":
                jTable1.setValueAt("DeLorian", 2, 1);
                break;
            case "1":
                jTable1.setValueAt("Chevrolet Impala", 2, 1);
                break;
            case "2":
                jTable1.setValueAt("Nissan Skyline GT-R", 2, 1);
                break;
            case "3":
                jTable1.setValueAt("Chevrolet Camaro", 2, 1);
                break;
            case "4":
                jTable1.setValueAt("General Lee", 2, 1);
                break;
            case "5":
                jTable1.setValueAt("Batmobile", 2, 1);
                break;
            case "6":
                jTable1.setValueAt("Dodge Charger", 2, 1);
                break;
        }
    }//GEN-LAST:event_jFrame5WindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
